import Testing
import Foundation
@testable import OQS

// KAT tests MUST run isolated from all other suites. liboqs's NIST-KAT DRBG is
// process-global: `.serialized` only orders tests *within* this suite, so a bare
// `swift test` races keygen in other suites against the seeded stream and fails
// nondeterministically. Run via: swift test --no-parallel --filter KATTests
// (CI runs the bulk suite with --skip KATTests and this suite separately).
//
// The committed digests in Vectors/kat_hashes.json are self-anchored regression
// locks generated by these wrappers under the deterministic seed — they detect
// future drift (e.g. a liboqs update changing output), not present-day
// correctness against external NIST vectors. vendor-liboqs.sh fetches upstream
// KATs into the gitignored UpstreamKATs/ for optional manual cross-checking.
@Suite(.serialized) struct KATTests {
    @Test("ML-KEM-512 KAT digest matches committed hash")
    func mlkem512KAT() throws {
        KAT.seedDeterministicRNG()
        defer { KAT.restoreSystemRNG() }

        let sk = try MLKEM512.PrivateKey()
        let sealed = try sk.publicKey.generateSharedSecret()
        let blob = sk.publicKey.rawRepresentation + sk.rawRepresentation
            + sealed.ciphertext + sealed.sharedSecret.rawRepresentation
        let digest = KAT.sha3_256Hex(blob)

        let expected = try KATHashes.shared.hash(for: "ML-KEM-512")
        #expect(digest == expected)
    }

    @Test("FrodoKEM-640-AES KAT digest matches committed hash")
    func frodo640aesKAT() throws {
        KAT.seedDeterministicRNG()
        defer { KAT.restoreSystemRNG() }
        let sk = try FrodoKEM640AES.PrivateKey()
        let sealed = try sk.publicKey.generateSharedSecret()
        let blob = sk.publicKey.rawRepresentation + sk.rawRepresentation
            + sealed.ciphertext + sealed.sharedSecret.rawRepresentation
        #expect(KAT.sha3_256Hex(blob) == (try KATHashes.shared.hash(for: "FrodoKEM-640-AES")))
    }

    @Test("NTRU-HPS-2048-509 KAT digest matches committed hash")
    func ntruhps2048509KAT() throws {
        KAT.seedDeterministicRNG()
        defer { KAT.restoreSystemRNG() }
        let sk = try NTRUHPS2048509.PrivateKey()
        let sealed = try sk.publicKey.generateSharedSecret()
        let blob = sk.publicKey.rawRepresentation + sk.rawRepresentation
            + sealed.ciphertext + sealed.sharedSecret.rawRepresentation
        #expect(KAT.sha3_256Hex(blob) == (try KATHashes.shared.hash(for: "NTRU-HPS-2048-509")))
    }

    @Test("sntrup761 KAT digest matches committed hash")
    func sntrup761KAT() throws {
        KAT.seedDeterministicRNG()
        defer { KAT.restoreSystemRNG() }
        let sk = try SNTRUP761.PrivateKey()
        let sealed = try sk.publicKey.generateSharedSecret()
        let blob = sk.publicKey.rawRepresentation + sk.rawRepresentation
            + sealed.ciphertext + sealed.sharedSecret.rawRepresentation
        #expect(KAT.sha3_256Hex(blob) == (try KATHashes.shared.hash(for: "sntrup761")))
    }
}
