/* GENERATED by scripts/vendor-liboqs.sh — do not edit. */
#define LEVEL 1
#define FUNC_PREFIX OQS_KEM_bike_l1
#include "functions_renaming.h"
#include "additional_r4/decode.c"
#include "additional_r4/decode_portable.c"
#include "additional_r4/error.c"
#include "additional_r4/gf2x_inv.c"
#include "additional_r4/gf2x_ksqr_portable.c"
#include "additional_r4/gf2x_mul.c"
#include "additional_r4/gf2x_mul_base_portable.c"
#include "additional_r4/gf2x_mul_portable.c"
#include "additional_r4/kem.c"
#include "additional_r4/sampling.c"
#include "additional_r4/sampling_portable.c"
#include "additional_r4/shake_prf.c"
#undef BITS_IN_BYTE
#include "additional_r4/utilities.c"
