/* GENERATED by scripts/vendor-liboqs.sh — do not edit. */
#define DILITHIUM_MODE 2
#include "pqcrystals-dilithium-standard_ml-dsa-44_ref/ntt.c"
#include "pqcrystals-dilithium-standard_ml-dsa-44_ref/packing.c"
#include "pqcrystals-dilithium-standard_ml-dsa-44_ref/poly.c"
#include "pqcrystals-dilithium-standard_ml-dsa-44_ref/polyvec.c"
#include "pqcrystals-dilithium-standard_ml-dsa-44_ref/reduce.c"
#include "pqcrystals-dilithium-standard_ml-dsa-44_ref/rounding.c"
#include "pqcrystals-dilithium-standard_ml-dsa-44_ref/sign.c"
#include "pqcrystals-dilithium-standard_ml-dsa-44_ref/symmetric-shake.c"
