/* GENERATED by scripts/vendor-liboqs.sh — do not edit. */
#define DILITHIUM_MODE 5
#include "pqcrystals-dilithium-standard_ml-dsa-87_ref/ntt.c"
#include "pqcrystals-dilithium-standard_ml-dsa-87_ref/packing.c"
#include "pqcrystals-dilithium-standard_ml-dsa-87_ref/poly.c"
#include "pqcrystals-dilithium-standard_ml-dsa-87_ref/polyvec.c"
#include "pqcrystals-dilithium-standard_ml-dsa-87_ref/reduce.c"
#include "pqcrystals-dilithium-standard_ml-dsa-87_ref/rounding.c"
#include "pqcrystals-dilithium-standard_ml-dsa-87_ref/sign.c"
#include "pqcrystals-dilithium-standard_ml-dsa-87_ref/symmetric-shake.c"
