/* GENERATED by scripts/vendor-liboqs.sh — do not edit. */
#define DILITHIUM_MODE 3
#include "pqcrystals-dilithium-standard_ml-dsa-65_ref/ntt.c"
#include "pqcrystals-dilithium-standard_ml-dsa-65_ref/packing.c"
#include "pqcrystals-dilithium-standard_ml-dsa-65_ref/poly.c"
#include "pqcrystals-dilithium-standard_ml-dsa-65_ref/polyvec.c"
#include "pqcrystals-dilithium-standard_ml-dsa-65_ref/reduce.c"
#include "pqcrystals-dilithium-standard_ml-dsa-65_ref/rounding.c"
#include "pqcrystals-dilithium-standard_ml-dsa-65_ref/sign.c"
#include "pqcrystals-dilithium-standard_ml-dsa-65_ref/symmetric-shake.c"
