/* GENERATED by scripts/vendor-liboqs.sh — do not edit. */
#define OPTIMISATION 1
#define v_SNOVA 24
#define o_SNOVA 5
#define l_SNOVA 4
#define sk_is_seed 1
#define PK_EXPAND_SHAKE 1
#include "snova_SNOVA_24_5_4_SHAKE_opt/oqs_snova.c"
#include "snova_SNOVA_24_5_4_SHAKE_opt/snova_aes.c"
#include "snova_SNOVA_24_5_4_SHAKE_opt/snova_common.c"
#include "snova_SNOVA_24_5_4_SHAKE_opt/snova_shake.c"
#include "snova_SNOVA_24_5_4_SHAKE_opt/snova.c"
