/* GENERATED by scripts/vendor-liboqs.sh — do not edit. */
#define OPTIMISATION 1
#define v_SNOVA 37
#define o_SNOVA 17
#define l_SNOVA 2
#define sk_is_seed 1
#define PK_EXPAND_SHAKE 0
#include "snova_SNOVA_37_17_2_opt/oqs_snova.c"
#include "snova_SNOVA_37_17_2_opt/snova_aes.c"
#include "snova_SNOVA_37_17_2_opt/snova_common.c"
#include "snova_SNOVA_37_17_2_opt/snova_shake.c"
#include "snova_SNOVA_37_17_2_opt/snova.c"
