/* GENERATED by scripts/vendor-liboqs.sh — do not edit. */
#define OPTIMISATION 1
#define v_SNOVA 49
#define o_SNOVA 11
#define l_SNOVA 3
#define sk_is_seed 1
#define PK_EXPAND_SHAKE 0
#include "snova_SNOVA_49_11_3_opt/oqs_snova.c"
#include "snova_SNOVA_49_11_3_opt/snova_aes.c"
#include "snova_SNOVA_49_11_3_opt/snova_common.c"
#include "snova_SNOVA_49_11_3_opt/snova_shake.c"
#include "snova_SNOVA_49_11_3_opt/snova.c"
