/* GENERATED by scripts/vendor-liboqs.sh — do not edit. */
#define OPTIMISATION 1
#define v_SNOVA 29
#define o_SNOVA 6
#define l_SNOVA 5
#define sk_is_seed 1
#define PK_EXPAND_SHAKE 0
#include "snova_SNOVA_29_6_5_opt/oqs_snova.c"
#include "snova_SNOVA_29_6_5_opt/snova_aes.c"
#include "snova_SNOVA_29_6_5_opt/snova_common.c"
#include "snova_SNOVA_29_6_5_opt/snova_shake.c"
#include "snova_SNOVA_29_6_5_opt/snova.c"
