/* GENERATED by scripts/vendor-liboqs.sh — do not edit. */
#define KYBER_K 4
#include "pqcrystals-kyber_kyber1024_ref/cbd.c"
#include "pqcrystals-kyber_kyber1024_ref/indcpa.c"
#include "pqcrystals-kyber_kyber1024_ref/kem.c"
#include "pqcrystals-kyber_kyber1024_ref/ntt.c"
#include "pqcrystals-kyber_kyber1024_ref/poly.c"
#include "pqcrystals-kyber_kyber1024_ref/polyvec.c"
#include "pqcrystals-kyber_kyber1024_ref/reduce.c"
#include "pqcrystals-kyber_kyber1024_ref/symmetric-shake.c"
#include "pqcrystals-kyber_kyber1024_ref/verify.c"
