/* GENERATED by scripts/vendor-liboqs.sh — do not edit. */
#define KYBER_K 2
#include "pqcrystals-kyber_kyber512_ref/cbd.c"
#include "pqcrystals-kyber_kyber512_ref/indcpa.c"
#include "pqcrystals-kyber_kyber512_ref/kem.c"
#include "pqcrystals-kyber_kyber512_ref/ntt.c"
#include "pqcrystals-kyber_kyber512_ref/poly.c"
#include "pqcrystals-kyber_kyber512_ref/polyvec.c"
#include "pqcrystals-kyber_kyber512_ref/reduce.c"
#include "pqcrystals-kyber_kyber512_ref/symmetric-shake.c"
#include "pqcrystals-kyber_kyber512_ref/verify.c"
