/* GENERATED by scripts/vendor-liboqs.sh — do not edit. */
#define KYBER_K 3
#include "pqcrystals-kyber_kyber768_ref/cbd.c"
#include "pqcrystals-kyber_kyber768_ref/indcpa.c"
#include "pqcrystals-kyber_kyber768_ref/kem.c"
#include "pqcrystals-kyber_kyber768_ref/ntt.c"
#include "pqcrystals-kyber_kyber768_ref/poly.c"
#include "pqcrystals-kyber_kyber768_ref/polyvec.c"
#include "pqcrystals-kyber_kyber768_ref/reduce.c"
#include "pqcrystals-kyber_kyber768_ref/symmetric-shake.c"
#include "pqcrystals-kyber_kyber768_ref/verify.c"
