/* GENERATED by scripts/vendor-liboqs.sh — do not edit. */
#define XMSS_PARAMS_NAMESPACE xmss_shake128_h16
#define HASH 4
#include "sig_stfl_xmss_functions.c"
#include "sig_stfl_xmss_shake128_h16.c"
#include "external/core_hash.c"
#include "external/hash.c"
#include "external/hash_address.c"
#include "external/params.c"
#include "external/utils.c"
#include "external/wots.c"
#include "external/xmss.c"
#include "external/xmss_commons.c"
#include "external/xmss_core_fast.c"
