/* GENERATED by scripts/vendor-liboqs.sh — do not edit. */
#define XMSS_PARAMS_NAMESPACE xmssmt_shake128_h20_2
#define HASH 4
#include "sig_stfl_xmssmt_functions.c"
#include "sig_stfl_xmssmt_shake128_h20_2.c"
#include "external/core_hash.c"
#include "external/hash.c"
#include "external/hash_address.c"
#include "external/params.c"
#include "external/utils.c"
#include "external/wots.c"
#include "external/xmss.c"
#include "external/xmss_commons.c"
#include "external/xmss_core_fast.c"
