/* GENERATED by scripts/vendor-liboqs.sh — do not edit. */
#define XMSS_PARAMS_NAMESPACE xmss_sha256_h10
#define HASH 3
#include "sig_stfl_xmss_functions.c"
#include "sig_stfl_xmss_sha256_h10.c"
#include "external/core_hash.c"
#include "external/hash.c"
#include "external/hash_address.c"
#include "external/params.c"
#include "external/utils.c"
#include "external/wots.c"
#include "external/xmss.c"
#include "external/xmss_commons.c"
#include "external/xmss_core_fast.c"
