/* GENERATED by scripts/vendor-liboqs.sh — do not edit. */
#define _OV256_184_72
#define _OV_PKC_SKC
#define _UTILS_OQS_
#include "pqov_ov_III_pkc_skc_ref/blas_matrix_ref.c"
#include "pqov_ov_III_pkc_skc_ref/blas_matrix.c"
#include "pqov_ov_III_pkc_skc_ref/ov_keypair_computation.c"
#include "pqov_ov_III_pkc_skc_ref/ov_keypair.c"
#include "pqov_ov_III_pkc_skc_ref/ov_publicmap.c"
#include "pqov_ov_III_pkc_skc_ref/ov.c"
#include "pqov_ov_III_pkc_skc_ref/parallel_matrix_op.c"
#include "pqov_ov_III_pkc_skc_ref/sign.c"
#include "pqov_ov_III_pkc_skc_ref/utils_hash.c"
#include "pqov_ov_III_pkc_skc_ref/utils_prng.c"
#include "pqov_ov_III_pkc_skc_ref/utils_randombytes.c"
