/* GENERATED by scripts/vendor-liboqs.sh — do not edit. */
#define _OV16_160_64
#define _OV_PKC
#define _UTILS_OQS_
#include "pqov_ov_Is_pkc_ref/blas_matrix_ref.c"
#include "pqov_ov_Is_pkc_ref/blas_matrix.c"
#include "pqov_ov_Is_pkc_ref/ov_keypair_computation.c"
#include "pqov_ov_Is_pkc_ref/ov_keypair.c"
#include "pqov_ov_Is_pkc_ref/ov_publicmap.c"
#include "pqov_ov_Is_pkc_ref/ov.c"
#include "pqov_ov_Is_pkc_ref/parallel_matrix_op.c"
#include "pqov_ov_Is_pkc_ref/sign.c"
#include "pqov_ov_Is_pkc_ref/utils_hash.c"
#include "pqov_ov_Is_pkc_ref/utils_prng.c"
#include "pqov_ov_Is_pkc_ref/utils_randombytes.c"
