/* GENERATED by scripts/vendor-liboqs.sh — do not edit. */
#define MAYO_VARIANT MAYO_5
#define MAYO_BUILD_TYPE_OPT
#define HAVE_RANDOMBYTES_NORETVAL
#define HAVE_STACKEFFICIENT
#include "pqmayo_mayo-5_opt/api.c"
#include "pqmayo_mayo-5_opt/arithmetic.c"
#include "pqmayo_mayo-5_opt/mayo.c"
#include "pqmayo_mayo-5_opt/params.c"
