/* GENERATED by scripts/vendor-liboqs.sh — do not edit. */
#define MAYO_VARIANT MAYO_1
#define MAYO_BUILD_TYPE_OPT
#define HAVE_RANDOMBYTES_NORETVAL
#define HAVE_STACKEFFICIENT
#include "pqmayo_mayo-1_opt/api.c"
#include "pqmayo_mayo-1_opt/arithmetic.c"
#include "pqmayo_mayo-1_opt/mayo.c"
#include "pqmayo_mayo-1_opt/params.c"
