/* GENERATED by scripts/vendor-liboqs.sh — do not edit. */
#define MAYO_VARIANT MAYO_2
#define MAYO_BUILD_TYPE_OPT
#define HAVE_RANDOMBYTES_NORETVAL
#include "pqmayo_mayo-2_opt/api.c"
#include "pqmayo_mayo-2_opt/arithmetic.c"
#include "pqmayo_mayo-2_opt/mayo.c"
#include "pqmayo_mayo-2_opt/params.c"
