#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
VERSION=$(cat "$REPO_ROOT/LIBOQS_VERSION")
DEST="$REPO_ROOT/Sources/Cliboqs"

echo "Vendoring liboqs $VERSION..."

if [ -d "$DEST/src" ]; then
    rm -rf "$DEST/src"
fi
# Preserve oqsconfig.h (manually maintained) across re-vendoring
if [ -f "$DEST/include/oqs/oqsconfig.h" ]; then
    cp "$DEST/include/oqs/oqsconfig.h" "$DEST/include/oqsconfig.h.bak"
fi
if [ -d "$DEST/include/oqs" ]; then
    rm -rf "$DEST/include/oqs"
fi

TMPDIR=$(mktemp -d)
TARBALL="$TMPDIR/liboqs-$VERSION.tar.gz"
curl -sL "https://github.com/open-quantum-safe/liboqs/archive/refs/tags/$VERSION.tar.gz" -o "$TARBALL"
tar -xzf "$TARBALL" -C "$TMPDIR"
LIBOQS_SRC="$TMPDIR/liboqs-$VERSION/src"

mkdir -p "$DEST/src"
cp -R "$LIBOQS_SRC/common" "$DEST/src/"
cp -R "$LIBOQS_SRC/kem" "$DEST/src/"
cp -R "$LIBOQS_SRC/sig" "$DEST/src/"
cp -R "$LIBOQS_SRC/sig_stfl" "$DEST/src/"

mkdir -p "$DEST/include/oqs"

# Core public headers
cp "$LIBOQS_SRC/oqs.h" "$DEST/include/oqs/"
cp "$LIBOQS_SRC/common/common.h" "$DEST/include/oqs/"
cp "$LIBOQS_SRC/common/rand/rand.h" "$DEST/include/oqs/"
cp "$LIBOQS_SRC/common/rand/rand_nist.h" "$DEST/include/oqs/" 2>/dev/null || true
cp "$LIBOQS_SRC/kem/kem.h" "$DEST/include/oqs/"
cp "$LIBOQS_SRC/sig/sig.h" "$DEST/include/oqs/"
cp "$LIBOQS_SRC/sig_stfl/sig_stfl.h" "$DEST/include/oqs/"
cp "$LIBOQS_SRC/sig_stfl/xmss/sig_stfl_xmss.h" "$DEST/include/oqs/"
cp "$LIBOQS_SRC/sig_stfl/lms/sig_stfl_lms.h" "$DEST/include/oqs/"
cp "$LIBOQS_SRC/common/aes/aes_ops.h" "$DEST/include/oqs/"
cp "$LIBOQS_SRC/common/aes/aes.h" "$DEST/include/oqs/"
cp "$LIBOQS_SRC/common/sha2/sha2_ops.h" "$DEST/include/oqs/"
cp "$LIBOQS_SRC/common/sha2/sha2.h" "$DEST/include/oqs/"
cp "$LIBOQS_SRC/common/sha3/sha3_ops.h" "$DEST/include/oqs/"
cp "$LIBOQS_SRC/common/sha3/sha3.h" "$DEST/include/oqs/"
cp "$LIBOQS_SRC/common/sha3/sha3x4_ops.h" "$DEST/include/oqs/"
cp "$LIBOQS_SRC/common/sha3/sha3x4.h" "$DEST/include/oqs/"

# Per-algorithm public headers (kem_*.h, sig_*.h at algorithm directory level)
for dir in "$LIBOQS_SRC"/kem/*/; do
    for h in "$dir"kem_*.h; do
        [ -f "$h" ] && cp "$h" "$DEST/include/oqs/"
    done
done
for dir in "$LIBOQS_SRC"/sig/*/; do
    for h in "$dir"sig_*.h; do
        [ -f "$h" ] && cp "$h" "$DEST/include/oqs/"
    done
done

# generate_unity <family_dir> <variant_dir_glob> [extra_defines...]
# Emits one unity_<variant>.c per matching variant directory that #includes
# every .c file directly inside that directory (non-recursive). Concatenating
# per-variant sources into one TU avoids SPM's flat per-basename object
# collisions across variants that share filenames (poly.c, ntt.c, ...).
# extra_defines are emitted as `#define <token>` at the top of the TU (note:
# pass "NAME VAL" with a space, not CMake's -DNAME=VAL form) so per-variant
# compile-time parameters that liboqs's CMake passes via -D — which SPM cannot
# supply per-file — are baked into the TU ahead of the variant's params.h
# (whose defaults are #ifndef-guarded).
generate_unity() {
    local family_dir="$1"; shift
    local glob="$1"; shift
    local defines=("$@")
    local vdir base unity f d
    for vdir in "$DEST/$family_dir"/$glob; do
        [ -d "$vdir" ] || continue
        base="$(basename "$vdir")"
        unity="$DEST/$family_dir/unity_${base}.c"
        {
            echo "/* GENERATED by scripts/vendor-liboqs.sh — do not edit. */"
            for d in "${defines[@]}"; do echo "#define $d"; done
            for f in "$vdir"/*.c; do
                [ -e "$f" ] || continue
                echo "#include \"${base}/$(basename "$f")\""
            done
        } > "$unity"
        echo "  generated $unity"
    done
}

# ML-DSA variants select their namespace from DILITHIUM_MODE (CMake
# -DDILITHIUM_MODE=N). config.h defaults it to 2 (ML-DSA-44) under #ifndef, so
# 65/87 must override it or they emit ML-DSA-44's symbols. Values mirror
# src/sig/ml_dsa/CMakeLists.txt.
# localize_includes <family_dir> <variant_dir_glob>
# Rewrites `#include <X.h>` -> `#include "X.h"` in every .c/.h inside each
# matching variant dir, but ONLY when X.h actually exists in that same dir.
# MAYO angle-includes its own variant-local headers (mayo.h, api.h, arithmetic.h,
# ...); angle includes never search the includer's directory, and SPM cannot add
# a per-file -I, so the unity TU (which lives one level up in the family dir)
# can't resolve them. A global -I per variant is unsafe: api.h differs per
# variant (different CRYPTO_*BYTES) and generic basenames (arithmetic.h, mem.h)
# would shadow other families. Quote includes resolve relative to the including
# file's own dir, so each variant picks up its OWN headers with no collision.
# The existence test leaves true externals (fips202.h, randombytes.h, aes.h,
# std*.h, the avx2/neon-only m4_/shuffle_arithmetic.h) as angle includes.
localize_includes() {
    local family_dir="$1"; shift
    local glob="$1"; shift
    local vdir f hdr
    for vdir in "$DEST/$family_dir"/$glob; do
        [ -d "$vdir" ] || continue
        for f in "$vdir"/*.c "$vdir"/*.h; do
            [ -e "$f" ] || continue
            for hdr in "$vdir"/*.h; do
                [ -e "$hdr" ] || continue
                hdr="$(basename "$hdr")"
                # Escape dots for the regex; rewrite only the local-header angle form.
                local esc="${hdr//./\\.}"
                sed -i.bak -E "s|#include[[:space:]]*<${esc}>|#include \"${hdr}\"|g" "$f"
                rm -f "$f.bak"
            done
        done
    done
    echo "  localized includes under $DEST/$family_dir/$glob"
}

generate_unity "src/sig/ml_dsa" "pqcrystals-dilithium-standard_ml-dsa-44_ref" "DILITHIUM_MODE 2"
generate_unity "src/sig/ml_dsa" "pqcrystals-dilithium-standard_ml-dsa-65_ref" "DILITHIUM_MODE 3"
generate_unity "src/sig/ml_dsa" "pqcrystals-dilithium-standard_ml-dsa-87_ref" "DILITHIUM_MODE 5"

# Kyber variants take their security level from KYBER_K (CMake -DKYBER_K=N).
generate_unity "src/kem/kyber" "pqcrystals-kyber_kyber512_ref"  "KYBER_K 2"
generate_unity "src/kem/kyber" "pqcrystals-kyber_kyber768_ref"  "KYBER_K 3"
generate_unity "src/kem/kyber" "pqcrystals-kyber_kyber1024_ref" "KYBER_K 4"

# SNOVA variants take v/o/l + sk_is_seed + PK_EXPAND_SHAKE + OPTIMISATION from
# CMake -D flags. OPTIMISATION must be 1 (opt path); params.h defaults it to 2
# (SIMD). Values mirror src/sig/snova/CMakeLists.txt.
generate_unity "src/sig/snova" "snova_SNOVA_24_5_4_opt"          "OPTIMISATION 1" "v_SNOVA 24" "o_SNOVA 5"  "l_SNOVA 4" "sk_is_seed 1" "PK_EXPAND_SHAKE 0"
generate_unity "src/sig/snova" "snova_SNOVA_24_5_4_SHAKE_opt"    "OPTIMISATION 1" "v_SNOVA 24" "o_SNOVA 5"  "l_SNOVA 4" "sk_is_seed 1" "PK_EXPAND_SHAKE 1"
generate_unity "src/sig/snova" "snova_SNOVA_24_5_4_esk_opt"      "OPTIMISATION 1" "v_SNOVA 24" "o_SNOVA 5"  "l_SNOVA 4" "sk_is_seed 0" "PK_EXPAND_SHAKE 0"
generate_unity "src/sig/snova" "snova_SNOVA_24_5_4_SHAKE_esk_opt" "OPTIMISATION 1" "v_SNOVA 24" "o_SNOVA 5"  "l_SNOVA 4" "sk_is_seed 0" "PK_EXPAND_SHAKE 1"
generate_unity "src/sig/snova" "snova_SNOVA_24_5_5_opt"          "OPTIMISATION 1" "v_SNOVA 24" "o_SNOVA 5"  "l_SNOVA 5" "sk_is_seed 1" "PK_EXPAND_SHAKE 0"
generate_unity "src/sig/snova" "snova_SNOVA_25_8_3_opt"          "OPTIMISATION 1" "v_SNOVA 25" "o_SNOVA 8"  "l_SNOVA 3" "sk_is_seed 1" "PK_EXPAND_SHAKE 0"
generate_unity "src/sig/snova" "snova_SNOVA_29_6_5_opt"          "OPTIMISATION 1" "v_SNOVA 29" "o_SNOVA 6"  "l_SNOVA 5" "sk_is_seed 1" "PK_EXPAND_SHAKE 0"
generate_unity "src/sig/snova" "snova_SNOVA_37_8_4_opt"          "OPTIMISATION 1" "v_SNOVA 37" "o_SNOVA 8"  "l_SNOVA 4" "sk_is_seed 1" "PK_EXPAND_SHAKE 0"
generate_unity "src/sig/snova" "snova_SNOVA_37_17_2_opt"         "OPTIMISATION 1" "v_SNOVA 37" "o_SNOVA 17" "l_SNOVA 2" "sk_is_seed 1" "PK_EXPAND_SHAKE 0"
generate_unity "src/sig/snova" "snova_SNOVA_49_11_3_opt"         "OPTIMISATION 1" "v_SNOVA 49" "o_SNOVA 11" "l_SNOVA 3" "sk_is_seed 1" "PK_EXPAND_SHAKE 0"
generate_unity "src/sig/snova" "snova_SNOVA_56_25_2_opt"         "OPTIMISATION 1" "v_SNOVA 56" "o_SNOVA 25" "l_SNOVA 2" "sk_is_seed 1" "PK_EXPAND_SHAKE 0"
generate_unity "src/sig/snova" "snova_SNOVA_60_10_4_opt"         "OPTIMISATION 1" "v_SNOVA 60" "o_SNOVA 10" "l_SNOVA 4" "sk_is_seed 1" "PK_EXPAND_SHAKE 0"

# MAYO opt variants select their parameter set from MAYO_VARIANT (CMake
# -DMAYO_VARIANT=MAYO_N). Values mirror src/sig/mayo/CMakeLists.txt; MAYO-2 is
# the only variant that omits HAVE_STACKEFFICIENT. MAYO angle-includes its own
# variant-local headers, so localize_includes must run BEFORE generate_unity so
# the merged unity TU can resolve them via quote includes.
localize_includes "src/sig/mayo" "pqmayo_mayo-1_opt"
localize_includes "src/sig/mayo" "pqmayo_mayo-2_opt"
localize_includes "src/sig/mayo" "pqmayo_mayo-3_opt"
localize_includes "src/sig/mayo" "pqmayo_mayo-5_opt"
generate_unity "src/sig/mayo" "pqmayo_mayo-1_opt" "MAYO_VARIANT MAYO_1" "MAYO_BUILD_TYPE_OPT" "HAVE_RANDOMBYTES_NORETVAL" "HAVE_STACKEFFICIENT"
generate_unity "src/sig/mayo" "pqmayo_mayo-2_opt" "MAYO_VARIANT MAYO_2" "MAYO_BUILD_TYPE_OPT" "HAVE_RANDOMBYTES_NORETVAL"
generate_unity "src/sig/mayo" "pqmayo_mayo-3_opt" "MAYO_VARIANT MAYO_3" "MAYO_BUILD_TYPE_OPT" "HAVE_RANDOMBYTES_NORETVAL" "HAVE_STACKEFFICIENT"
generate_unity "src/sig/mayo" "pqmayo_mayo-5_opt" "MAYO_VARIANT MAYO_5" "MAYO_BUILD_TYPE_OPT" "HAVE_RANDOMBYTES_NORETVAL" "HAVE_STACKEFFICIENT"

# Fetch upstream KAT hash manifests for cross-checking (best-effort, reference-only).
# Kept OUTSIDE Tests/OQSTests/Vectors so the test bundle stays small.
KAT_DIR="$REPO_ROOT/Tests/OQSTests/UpstreamKATs"
mkdir -p "$KAT_DIR"
if [ -d "$TMPDIR/liboqs-$VERSION/tests/KATs" ]; then
    cp -R "$TMPDIR/liboqs-$VERSION/tests/KATs" "$KAT_DIR/" 2>/dev/null || true
fi

rm -rf "$TMPDIR"

# Restore oqsconfig.h
if [ -f "$DEST/include/oqsconfig.h.bak" ]; then
    cp "$DEST/include/oqsconfig.h.bak" "$DEST/include/oqs/oqsconfig.h"
    rm "$DEST/include/oqsconfig.h.bak"
fi

echo "Done. Vendored liboqs $VERSION into $DEST"
