#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
VERSION=$(cat "$REPO_ROOT/LIBOQS_VERSION")
DEST="$REPO_ROOT/Sources/Cliboqs"

echo "Vendoring liboqs $VERSION..."

if [ -d "$DEST/src" ]; then
    rm -rf "$DEST/src"
fi
# Preserve oqsconfig.h (manually maintained) across re-vendoring
if [ -f "$DEST/include/oqs/oqsconfig.h" ]; then
    cp "$DEST/include/oqs/oqsconfig.h" "$DEST/include/oqsconfig.h.bak"
fi
if [ -d "$DEST/include/oqs" ]; then
    rm -rf "$DEST/include/oqs"
fi

TMPDIR=$(mktemp -d)
TARBALL="$TMPDIR/liboqs-$VERSION.tar.gz"
curl -sL "https://github.com/open-quantum-safe/liboqs/archive/refs/tags/$VERSION.tar.gz" -o "$TARBALL"
tar -xzf "$TARBALL" -C "$TMPDIR"
LIBOQS_SRC="$TMPDIR/liboqs-$VERSION/src"

mkdir -p "$DEST/src"
cp -R "$LIBOQS_SRC/common" "$DEST/src/"
cp -R "$LIBOQS_SRC/kem" "$DEST/src/"
cp -R "$LIBOQS_SRC/sig" "$DEST/src/"
cp -R "$LIBOQS_SRC/sig_stfl" "$DEST/src/"

mkdir -p "$DEST/include/oqs"

# Core public headers
cp "$LIBOQS_SRC/oqs.h" "$DEST/include/oqs/"
cp "$LIBOQS_SRC/common/common.h" "$DEST/include/oqs/"
cp "$LIBOQS_SRC/common/rand/rand.h" "$DEST/include/oqs/"
cp "$LIBOQS_SRC/common/rand/rand_nist.h" "$DEST/include/oqs/" 2>/dev/null || true
cp "$LIBOQS_SRC/kem/kem.h" "$DEST/include/oqs/"
cp "$LIBOQS_SRC/sig/sig.h" "$DEST/include/oqs/"
cp "$LIBOQS_SRC/sig_stfl/sig_stfl.h" "$DEST/include/oqs/"
cp "$LIBOQS_SRC/sig_stfl/xmss/sig_stfl_xmss.h" "$DEST/include/oqs/"
cp "$LIBOQS_SRC/sig_stfl/lms/sig_stfl_lms.h" "$DEST/include/oqs/"
cp "$LIBOQS_SRC/common/aes/aes_ops.h" "$DEST/include/oqs/"
cp "$LIBOQS_SRC/common/aes/aes.h" "$DEST/include/oqs/"
cp "$LIBOQS_SRC/common/sha2/sha2_ops.h" "$DEST/include/oqs/"
cp "$LIBOQS_SRC/common/sha2/sha2.h" "$DEST/include/oqs/"
cp "$LIBOQS_SRC/common/sha3/sha3_ops.h" "$DEST/include/oqs/"
cp "$LIBOQS_SRC/common/sha3/sha3.h" "$DEST/include/oqs/"
cp "$LIBOQS_SRC/common/sha3/sha3x4_ops.h" "$DEST/include/oqs/"
cp "$LIBOQS_SRC/common/sha3/sha3x4.h" "$DEST/include/oqs/"

# Per-algorithm public headers (kem_*.h, sig_*.h at algorithm directory level)
for dir in "$LIBOQS_SRC"/kem/*/; do
    for h in "$dir"kem_*.h; do
        [ -f "$h" ] && cp "$h" "$DEST/include/oqs/"
    done
done
for dir in "$LIBOQS_SRC"/sig/*/; do
    for h in "$dir"sig_*.h; do
        [ -f "$h" ] && cp "$h" "$DEST/include/oqs/"
    done
done

# generate_unity <family_dir> <variant_dir_glob> [extra_defines...]
# Emits one unity_<variant>.c per matching variant directory that #includes
# every .c file directly inside that directory (non-recursive). Concatenating
# per-variant sources into one TU avoids SPM's flat per-basename object
# collisions across variants that share filenames (poly.c, ntt.c, ...).
# extra_defines are emitted as `#define <token>` at the top of the TU (note:
# pass "NAME VAL" with a space, not CMake's -DNAME=VAL form) so per-variant
# compile-time parameters that liboqs's CMake passes via -D — which SPM cannot
# supply per-file — are baked into the TU ahead of the variant's params.h
# (whose defaults are #ifndef-guarded).
generate_unity() {
    local family_dir="$1"; shift
    local glob="$1"; shift
    local defines=("$@")
    local vdir base unity f d
    for vdir in "$DEST/$family_dir"/$glob; do
        [ -d "$vdir" ] || continue
        base="$(basename "$vdir")"
        unity="$DEST/$family_dir/unity_${base}.c"
        {
            echo "/* GENERATED by scripts/vendor-liboqs.sh — do not edit. */"
            for d in "${defines[@]}"; do echo "#define $d"; done
            for f in "$vdir"/*.c; do
                [ -e "$f" ] || continue
                echo "#include \"${base}/$(basename "$f")\""
            done
        } > "$unity"
        echo "  generated $unity"
    done
}

# ML-DSA variants select their namespace from DILITHIUM_MODE (CMake
# -DDILITHIUM_MODE=N). config.h defaults it to 2 (ML-DSA-44) under #ifndef, so
# 65/87 must override it or they emit ML-DSA-44's symbols. Values mirror
# src/sig/ml_dsa/CMakeLists.txt.
generate_unity "src/sig/ml_dsa" "pqcrystals-dilithium-standard_ml-dsa-44_ref" "DILITHIUM_MODE 2"
generate_unity "src/sig/ml_dsa" "pqcrystals-dilithium-standard_ml-dsa-65_ref" "DILITHIUM_MODE 3"
generate_unity "src/sig/ml_dsa" "pqcrystals-dilithium-standard_ml-dsa-87_ref" "DILITHIUM_MODE 5"

# Kyber variants take their security level from KYBER_K (CMake -DKYBER_K=N).
generate_unity "src/kem/kyber" "pqcrystals-kyber_kyber512_ref"  "KYBER_K 2"
generate_unity "src/kem/kyber" "pqcrystals-kyber_kyber768_ref"  "KYBER_K 3"
generate_unity "src/kem/kyber" "pqcrystals-kyber_kyber1024_ref" "KYBER_K 4"

# SNOVA variants take v/o/l + sk_is_seed + PK_EXPAND_SHAKE + OPTIMISATION from
# CMake -D flags. OPTIMISATION must be 1 (opt path); params.h defaults it to 2
# (SIMD). Values mirror src/sig/snova/CMakeLists.txt.
generate_unity "src/sig/snova" "snova_SNOVA_24_5_4_opt"          "OPTIMISATION 1" "v_SNOVA 24" "o_SNOVA 5"  "l_SNOVA 4" "sk_is_seed 1" "PK_EXPAND_SHAKE 0"
generate_unity "src/sig/snova" "snova_SNOVA_24_5_4_SHAKE_opt"    "OPTIMISATION 1" "v_SNOVA 24" "o_SNOVA 5"  "l_SNOVA 4" "sk_is_seed 1" "PK_EXPAND_SHAKE 1"
generate_unity "src/sig/snova" "snova_SNOVA_24_5_4_esk_opt"      "OPTIMISATION 1" "v_SNOVA 24" "o_SNOVA 5"  "l_SNOVA 4" "sk_is_seed 0" "PK_EXPAND_SHAKE 0"
generate_unity "src/sig/snova" "snova_SNOVA_24_5_4_SHAKE_esk_opt" "OPTIMISATION 1" "v_SNOVA 24" "o_SNOVA 5"  "l_SNOVA 4" "sk_is_seed 0" "PK_EXPAND_SHAKE 1"
generate_unity "src/sig/snova" "snova_SNOVA_24_5_5_opt"          "OPTIMISATION 1" "v_SNOVA 24" "o_SNOVA 5"  "l_SNOVA 5" "sk_is_seed 1" "PK_EXPAND_SHAKE 0"
generate_unity "src/sig/snova" "snova_SNOVA_25_8_3_opt"          "OPTIMISATION 1" "v_SNOVA 25" "o_SNOVA 8"  "l_SNOVA 3" "sk_is_seed 1" "PK_EXPAND_SHAKE 0"
generate_unity "src/sig/snova" "snova_SNOVA_29_6_5_opt"          "OPTIMISATION 1" "v_SNOVA 29" "o_SNOVA 6"  "l_SNOVA 5" "sk_is_seed 1" "PK_EXPAND_SHAKE 0"
generate_unity "src/sig/snova" "snova_SNOVA_37_8_4_opt"          "OPTIMISATION 1" "v_SNOVA 37" "o_SNOVA 8"  "l_SNOVA 4" "sk_is_seed 1" "PK_EXPAND_SHAKE 0"
generate_unity "src/sig/snova" "snova_SNOVA_37_17_2_opt"         "OPTIMISATION 1" "v_SNOVA 37" "o_SNOVA 17" "l_SNOVA 2" "sk_is_seed 1" "PK_EXPAND_SHAKE 0"
generate_unity "src/sig/snova" "snova_SNOVA_49_11_3_opt"         "OPTIMISATION 1" "v_SNOVA 49" "o_SNOVA 11" "l_SNOVA 3" "sk_is_seed 1" "PK_EXPAND_SHAKE 0"
generate_unity "src/sig/snova" "snova_SNOVA_56_25_2_opt"         "OPTIMISATION 1" "v_SNOVA 56" "o_SNOVA 25" "l_SNOVA 2" "sk_is_seed 1" "PK_EXPAND_SHAKE 0"
generate_unity "src/sig/snova" "snova_SNOVA_60_10_4_opt"         "OPTIMISATION 1" "v_SNOVA 60" "o_SNOVA 10" "l_SNOVA 4" "sk_is_seed 1" "PK_EXPAND_SHAKE 0"

# MAYO opt variants select their parameter set from MAYO_VARIANT (CMake
# -DMAYO_VARIANT=MAYO_N). MAYO angle-includes its own variant-local headers
# (mayo.h, api.h, params.h, ...) whose sizes differ per variant, so they cannot
# share a flat include path. Rather than rewrite the upstream sources, each opt
# variant is compiled as its own SPM sub-target (CliboqsMAYO{1,2,3,5} in
# Package.swift) with its own directory on the header search path and the
# per-variant -D parameter defines, leaving the upstream sources pristine.

# UOV (oil-and-vinegar) variants select their param triple (_OVk_v_o), public-
# key/secret-key compression mode (_OV_CLASSIC / _OV_PKC / _OV_PKC_SKC), and
# hash backend from CMake -D flags. We pin _UTILS_OQS_ so utils_hash.c uses
# liboqs's bundled SHA3 (<oqs/sha3.h>) instead of OpenSSL, keeping the package
# dependency-free. UOV quote-includes its own variant-local headers, so no
# localize_includes is needed. Values mirror src/sig/uov/CMakeLists.txt.
generate_unity "src/sig/uov" "pqov_ov_Is_ref"           "_OV16_160_64"  "_OV_CLASSIC"  "_UTILS_OQS_"
generate_unity "src/sig/uov" "pqov_ov_Ip_ref"           "_OV256_112_44" "_OV_CLASSIC"  "_UTILS_OQS_"
generate_unity "src/sig/uov" "pqov_ov_III_ref"          "_OV256_184_72" "_OV_CLASSIC"  "_UTILS_OQS_"
generate_unity "src/sig/uov" "pqov_ov_V_ref"            "_OV256_244_96" "_OV_CLASSIC"  "_UTILS_OQS_"
generate_unity "src/sig/uov" "pqov_ov_Is_pkc_ref"       "_OV16_160_64"  "_OV_PKC"      "_UTILS_OQS_"
generate_unity "src/sig/uov" "pqov_ov_Ip_pkc_ref"       "_OV256_112_44" "_OV_PKC"      "_UTILS_OQS_"
generate_unity "src/sig/uov" "pqov_ov_III_pkc_ref"      "_OV256_184_72" "_OV_PKC"      "_UTILS_OQS_"
generate_unity "src/sig/uov" "pqov_ov_V_pkc_ref"        "_OV256_244_96" "_OV_PKC"      "_UTILS_OQS_"
generate_unity "src/sig/uov" "pqov_ov_Is_pkc_skc_ref"   "_OV16_160_64"  "_OV_PKC_SKC"  "_UTILS_OQS_"
generate_unity "src/sig/uov" "pqov_ov_Ip_pkc_skc_ref"   "_OV256_112_44" "_OV_PKC_SKC"  "_UTILS_OQS_"
generate_unity "src/sig/uov" "pqov_ov_III_pkc_skc_ref"  "_OV256_184_72" "_OV_PKC_SKC"  "_UTILS_OQS_"
generate_unity "src/sig/uov" "pqov_ov_V_pkc_skc_ref"    "_OV256_244_96" "_OV_PKC_SKC"  "_UTILS_OQS_"

# BIKE keeps ALL sources in one additional_r4 dir, compiled three times with a
# different LEVEL/FUNC_PREFIX (CMake -DLEVEL=N -DFUNC_PREFIX=OQS_KEM_bike_lN).
# Emit one unity TU per level that bakes in those defines, force-includes
# functions_renaming.h (which liboqs's CMake supplies via `-include`, not a
# normal #include — it namespaces every symbol by FUNC_PREFIX, so it MUST be
# included after FUNC_PREFIX is defined and before the sources), then includes
# the portable .c set (avx2/avx512/pclmul/vpclmul + noop_main.c excluded). LEVEL
# drives the parameter sizes in bike_defs.h. The glue kem_bike.c compiles once
# (SPM, no -include) and references all three levels by full name — leave it.
generate_bike_unity() {
    local fam="src/kem/bike"
    local files=(decode.c decode_portable.c error.c gf2x_inv.c gf2x_ksqr_portable.c gf2x_mul.c gf2x_mul_base_portable.c gf2x_mul_portable.c kem.c sampling.c sampling_portable.c shake_prf.c utilities.c)
    local lvl f
    for lvl in 1 3 5; do
        local out="$DEST/$fam/unity_bike_l${lvl}.c"
        {
            echo "/* GENERATED by scripts/vendor-liboqs.sh — do not edit. */"
            echo "#define LEVEL ${lvl}"
            echo "#define FUNC_PREFIX OQS_KEM_bike_l${lvl}"
            echo "#include \"functions_renaming.h\""
            for f in "${files[@]}"; do
                # utilities.c and gf2x_ksqr_portable.c both define BITS_IN_BYTE
                # (8ULL vs (8)); equal values but concatenating them in one unity
                # TU trips -Wmacro-redefined. Clear it before utilities.c.
                if [ "$f" = "utilities.c" ]; then echo "#undef BITS_IN_BYTE"; fi
                echo "#include \"additional_r4/${f}\""
            done
        } > "$out"
        echo "  generated $out"
    done
}

generate_bike_unity

# Fetch upstream KAT hash manifests for cross-checking (best-effort, reference-only).
# Kept OUTSIDE Tests/OQSTests/Vectors so the test bundle stays small.
KAT_DIR="$REPO_ROOT/Tests/OQSTests/UpstreamKATs"
mkdir -p "$KAT_DIR"
if [ -d "$TMPDIR/liboqs-$VERSION/tests/KATs" ]; then
    cp -R "$TMPDIR/liboqs-$VERSION/tests/KATs" "$KAT_DIR/" 2>/dev/null || true
fi

rm -rf "$TMPDIR"

# Restore oqsconfig.h
if [ -f "$DEST/include/oqsconfig.h.bak" ]; then
    cp "$DEST/include/oqsconfig.h.bak" "$DEST/include/oqs/oqsconfig.h"
    rm "$DEST/include/oqsconfig.h.bak"
fi

echo "Done. Vendored liboqs $VERSION into $DEST"
